### ISSUE TITLE
Link isn't working!

### ISSUE THREAD

**Issue by Abhijeetbyte** [Baahu-007/Django-weatherapp#1]
Hi , there
I just wanted to try out the application, however the mentioned link of pythonanywhere is not working.
![Screenshot_2022-05-28-20-39-05-896~2](https://user-images.githubusercontent.com/80936610/170831418-05eebb09-1155-4c95-89f1-75b269c39bbc.jpeg)

**Comment by SeekerHub** [comment]
The hosting service I am using is pythonanywhere.com which is free and the site will be active for 3 months, due to which the current link is not working, thanks for reminding cause the time period is over , going to rehost the site in a few days.
Thanks!

**Comment by SeekerHub** [comment]
@Abhijeetbyte  I have hosted it again, you can now check it out,  sorry for the delay.
Thanks!
